apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Static Website</title>
    </head>
    <body>
      <h1>Welcome to the Static Website</h1>
      <p>This website is served by an Nginx server running in a Kubernetes cluster.</p>
      <p>Database Host: http://terraform-20250128180833670400000007.c5o4csuyg3zb.ap-south-1.rds.amazonaws.com:3306</p>
      <a href="http://terraform-20250128180833670400000007.c5o4csuyg3zb.ap-south-1.rds.amazonaws.com:3306">RDS Endpoint</a>
    </body>
    </html>