apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-demo
  region: ap-south-1
nodeGroups:
  - name: ng-1
    instanceType: mixed  # Set instanceType to "mixed" when using instancesDistribution
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instancesDistribution:
      maxPrice: 0.04  # Set a maximum price for spot instances as a float
      instanceTypes: ["t3.small", "t3.medium"]  # List of instance types to use
      onDemandBaseCapacity: 0  # Number of on-demand instances to launch before launching spot instances
      onDemandPercentageAboveBaseCapacity: 0  # Percentage of on-demand instances above the base capacity
      spotInstancePools: 2  # Number of spot instance pools to use
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true